POST http://localhost:4500/project
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3YzI1OThmLTNjNWQtNGU1ZS1hNzhkLWRhOWMxNjI0YTZiZiIsImVfbmFtZSI6IlBhdWwgU2FuZ2EiLCJlbWFpbCI6InBhdWwubnlhbWF3aUB0aGVqaXR1LmNvbSIsInJvbGUiOiJ1c2VyIiwiaXNzZW50Ijp0cnVlLCJwcm9maWxlIjpudWxsLCJpYXQiOjE2OTA0MDY1NzQsImV4cCI6MTY5MDQ0MjU3NH0.WHFKObc9Vb7HQemA8mtlp1aWIeBlpXhMGlG4MQYUGg0

{
    "project_name": "Build Dam",
    "description":"Build a Dam capable of holding 40000 litres",
    "project_location":"Nyeri",
    "startdate":"2023-7-25",
    "enddate":"2023/7/25"
}

### GET ALL PROJECTS
GET http://localhost:4500/project

### GET ONE PROJECT
GET http://localhost:4500/project/1464dda6-5651-4d3c-8c1c-527d977e15d8

### UPDATING PROJECT
PUT http://localhost:4500/project/1464dda6-5651-4d3c-8c1c-527d977e15d8
Content-Type: application/json

{
    "project_name": "Build A bridge",
    "description":"Build the nithi bridge",
    "project_location":"Tharaka Nithi",
    "startdate":"2023-7-25",
    "enddate":"2023-8-25"
}

###
DELETE http://localhost:4500/project/45a5c077-6e33-49b4-bf20-666b30a72404










#### EMPLOYEE ROUTES
POST http://localhost:4500/employee/register
Content-Type: application/json

{
    "e_name": "Augustus Mutambu",
    "email": "augkinyi@yopmail.com",
    "profile": "https://cdn.pixabay.com/photo/2018/07/31/21/58/lion-3576031_640.jpg",
    "password": "12345678"
}

### LOGIN
POST http://localhost:4500/employee/login
Content-Type: application/json

{
    "email": "paul.nyamawi@thejitu.com",
    "password": "12345678"
}

### READ TOKEN
GET http://localhost:4500/employee/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3YzI1OThmLTNjNWQtNGU1ZS1hNzhkLWRhOWMxNjI0YTZiZiIsImVfbmFtZSI6IlBhdWwgU2FuZ2EiLCJlbWFpbCI6InBhdWwubnlhbWF3aUB0aGVqaXR1LmNvbSIsInJvbGUiOiJ1c2VyIiwiaXNzZW50Ijp0cnVlLCJwcm9maWxlIjpudWxsLCJpYXQiOjE2OTA0NDc5NDksImV4cCI6MTY5MDQ4Mzk0OX0.P-yp3CPT3EGK4rsEOLwmjm2tV7cqoQsPppmXwHqZfEY