POST http://localhost:4500/project
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3YzI1OThmLTNjNWQtNGU1ZS1hNzhkLWRhOWMxNjI0YTZiZiIsImVfbmFtZSI6IlBhdWwgU2FuZ2EiLCJlbWFpbCI6InBhdWwubnlhbWF3aUB0aGVqaXR1LmNvbSIsInJvbGUiOiJ1c2VyIiwiaXNzZW50IjpmYWxzZSwiaWF0IjoxNjkwMzU3NjE3LCJleHAiOjE2OTAzOTM2MTd9.rwfMnVb0LiOq2GxdG1ZCtt3NNix5k-PcjWawTKNmbmA

{
    "project_name": "Build Dam",
    "description":"Build a Dam capable of holding 40000 litres",
    "project_location":"Nyeri",
    "startdate":"2023-7-25",
    "enddate":"2023/7/25"
}

### GET ALL PROJECTS
GET http://localhost:4500/project

### GET ONE PROJECT
GET http://localhost:4500/project/1464dda6-5651-4d3c-8c1c-527d977e15d8

### UPDATING PROJECT
PUT http://localhost:4500/project/1464dda6-5651-4d3c-8c1c-527d977e15d8
Content-Type: application/json

{
    "project_name": "Build A bridge",
    "description":"Build the nithi bridge",
    "project_location":"Tharaka Nithi",
    "startdate":"2023-7-25",
    "enddate":"2023-8-25"
}

###
DELETE http://localhost:4500/project/45a5c077-6e33-49b4-bf20-666b30a72404










#### EMPLOYEE ROUTES
POST http://localhost:4500/employee/register
Content-Type: application/json

{
    "e_name": "Benard Siloma",
    "email": "benard.masikonde@thejitu.com",
    "password": "12345678"
}

### LOGIN
POST http://localhost:4500/employee/login
Content-Type: application/json

{
    "email": "paul.nyamawi@thejitu.com",
    "password": "12345678"
}